### ISSUE TITLE
Questions par rapport au TP

### ISSUE THREAD

**Issue by Herman-Motcheyo** [Herman-Motcheyo/TP_RO_4GI#1]
Posez toutes les questions concernant le tp

**Comment by Hilary29** [comment]
S'il vous plait monsieur, est ce possible d'avoir une description claire du travail à rendre vendredi?

**Comment by Herman-Motcheyo** [comment]
Bonjour,

Je vous enverrai ce document ce soir.

**Comment by foupouagnigni** [comment]
Bonjour Mr , nous attendons le doccument relatif à la description du projet , les input , outputs (résultats attendus) svp .Ainsi que les languages de programmations non autorisés . Ajouter à cela le barème de notation . Merci Mr

**Comment by Herman-Motcheyo** [comment]
[TP_ Recherche Opérationnelle 4GI last.pdf](https://github.com/Herman-Motcheyo/TP_RO_4GI/files/15210353/TP_.Recherche.Operationnelle.4GI.last.pdf)
@foupouagnigni @Hilary29

**Comment by MAG-ENCRYPTION** [comment]
Bonjour Monsieur vu que vous permettez le Javascript est ce que l'on peut se permettre de mettre du Html et du Css pour rajouter du style et de la beauté ?

**Comment by Herman-Motcheyo** [comment]
Bonjour,

Oui oui

**Comment by MAG-ENCRYPTION** [comment]
Bonsoir Monsieur, en raison de quelques ambiguïtés dans mon groupe liées à la décision sur la technologie demandée pour le TP, ma question est la suivante : " Je voudrais savoir si React Js est une obligation ou bien on peut partir d'un code Javascript simple puis simplement y ajouter du html et du css pour le front "  Navré s'il y a redondance par rapport à la question du dessus mais je voudrais que dans mon groupe les choses soient claires ! 
Merci et bonne soirée !

**Comment by Herman-Motcheyo** [comment]
Bonjour,

En JavaScript vous avec la possibilité de faire du HTML CSS ou encore
utilisé reactjs en lien CDN.

**Comment by MAG-ENCRYPTION** [comment]
Une dernière question. C'est vrai que c'est mentionné dans le document [TP_ Recherche Opérationnelle 4GI last.pdf](https://github.com/Herman-Motcheyo/TP_RO_4GI/files/15210353/TP_.Recherche.Operationnelle.4GI.last.pdf) mais juste pour savoir : on aura aucune pénalité si on utilise Graphviz n'est ce pas ?

**Comment by Herman-Motcheyo** [comment]
bonjour,

OUI

Le jeu. 9 mai 2024 à 22:19, ALAIN GERARD ***@***.***> a
écrit :

**Comment by Zacharie-TENE** [comment]
Bonjour Monsieur.
Svp graphitz est il autorisé  finalement ? Dans le document oui mais verbalement vous avez refusé  avant.

**Comment by Herman-Motcheyo** [comment]
C'est autorisé et c'est dit dans le document
